name: stopwatch
description: Application for tracking time

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #toast: ^0.1.5
  fluttertoast: ^8.0.8
  path_provider: ^2.0.5
  scoped_model: ^2.0.0-nullsafety.0
  rate_my_app: ^1.1.1
  launch_review: ^3.0.1
  #preferences: ^5.0.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  shared_preferences: ^2.0.8
  #simple_search_bar: ^0.1.7
  #flutter_widgets: ^0.1.12
  after_layout: ^1.1.0
  scrollable_positioned_list: ^0.2.2
  indexed_list_view: ^2.0.1
  provider: ^6.0.1
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.1
  equatable: ^2.0.3
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0
  csv: ^5.0.0
  datetime_picker_formfield: ^2.0.0
  #moor_db_viewer: ^4.4.0
  tuple: ^2.0.0
  #get_it: ^7.2.0
  soundpool: ^2.2.0
  vibration: ^1.7.4-nullsafety.0
  validators: ^3.0.0
  flutter_email_sender: ^5.0.2
  #esys_flutter_share: ^1.0.2
  share_plus: ^3.0.4
  google_fonts: ^2.1.0
  wakelock: ^0.5.6
  visibility_detector: ^0.2.0
  in_app_purchase: ^1.0.9
  url_launcher: ^6.0.12
  package_info: ^2.0.2
  multiselect_scope: ^0.2.0
  extended_theme: ^0.2.0
  metro_appbar: ^0.2.0
  collection: ^1.15.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  #sqflite_common_ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  bloc_test: ^8.3.0
  analyzer: ^2.6.0
  drift_dev: ^1.0.2
  build_runner: ^2.1.4
  mockito: ^5.0.16
  # sqflite_ffi_test:
  #   git:
  #     url: git://github.com/tekartik/sqflite_more
  #     ref: dart2
  #     path: sqflite_ffi_test

  flutter_launcher_icons: ^0.9.2
  sqflite_common_ffi:

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/logo_back.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/logo_fore.png" # only available for Android 8.0 devices and above

# flutter pub run flutter_launcher_icons:main
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/sound1.wav
    - assets/sounds/sound2.wav
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
