// Shared Preference keys
const PREF_KEEP_SCREEN_AWAKE = 'pref_keep_screen_awake';
const PREF_SAVE_MEASURES = 'pref_save_measures';
const PREF_THEME = 'pref_theme';
const PREF_VIBRATION = 'pref_vibration';
const PREF_SOUND = 'pref_sound';
const DATABASE_NAME = 'database.sqlite';
const PRO_PACKAGE = 'pro_package';
const MAX_FREE_MEASURES = 3;