// Shared Preference keys
const prefKeepScreenAwake = 'pref_keep_screen_awake';
const prefSaveMeasures = 'pref_save_measures';
const prefTheme = 'pref_theme';
const prefVibration = 'pref_vibration';
const prefSound = 'pref_sound';
const databaseName = 'database.sqlite';
const proPackage = 'pro_package';
const maxFreeMeasures = 3;
